# Generated by Django 3.2.8 on 2021-10-09 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20211008_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='started_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
