# Generated by Django 3.2.8 on 2021-10-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_group_started_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='members.Group'),
        ),
    ]
