# Generated by Django 5.1.3 on 2024-12-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='general location',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('address', 'city', 'state', 'postal_code', 'country'), name='unique_location'),
        ),
    ]
