# Generated by Django 3.2.8 on 2021-10-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AddField(
            model_name='group',
            name='genres',
            field=models.ManyToManyField(to='bandshare.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(to='bandshare.Genre'),
        ),
    ]
