# Generated by Django 5.1.3 on 2024-12-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandshare', '0002_remove_location_general_location_location_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
