# Generated by Django 5.1.3 on 2024-12-02 18:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandshare', '0003_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('release_date', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('', 'Not Specified'), ('A', 'A Major'), ('B♭', 'Bb Major'), ('B', 'B Major'), ('C', 'C Major'), ('D♭', 'Db Major'), ('D', 'D Major'), ('E♭', 'Eb Major'), ('E', 'E Major'), ('F', 'F Major'), ('F♯', 'Fs Major'), ('G', 'G Major'), ('A♭', 'Ab Major'), ('Am', 'A Minor'), ('B♭m', 'Bb Minor'), ('Bm', 'B Minor'), ('Cm', 'C Minor'), ('C♯m', 'Cs Minor'), ('Dm', 'D Minor'), ('D♯m', 'Ds Minor'), ('Em', 'E Minor'), ('Fm', 'F Minor'), ('F♯m', 'Fs Minor'), ('Gm', 'G Minor'), ('G♯m', 'Gs Minor')], default='', max_length=3)),
                ('time_signature', models.CharField(choices=[('', 'Not Specified'), ('2/2', 'Two Two'), ('2/4', 'Two Four'), ('3/4', 'Three Four'), ('4/4', 'Four Four'), ('6/8', 'Six Eight'), ('9/8', 'Nine Eight'), ('12/8', 'Twelve Eight'), ('5/4', 'Five Four')], default='4/4', max_length=4)),
                ('bpm', models.IntegerField(default=120, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('time_seconds', models.DurationField(default=datetime.timedelta(seconds=180), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=3600))])),
                ('artist', models.ManyToManyField(to='bandshare.artist')),
                ('genres', models.ManyToManyField(to='bandshare.genre')),
            ],
        ),
    ]
