# Generated by Django 3.2.8 on 2021-10-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandshare', '0004_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bio',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
