# Generated by Django 5.1.3 on 2024-12-02 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandshare', '0004_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('owner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandshare.group')),
                ('songs', models.ManyToManyField(blank=True, to='bandshare.song')),
            ],
        ),
    ]
