# Generated by Django 3.2.8 on 2021-10-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandshare', '0007_auto_20211020_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='bandshare.Instrument'),
        ),
    ]
